language: php

sudo: false

php:
 - '7.0'

before_install:
 - sed -i 's/git@github.com:/https:\/\/GH_TOKEN@github.com\//' deploy.sh
 - sed -i 's/git@github.com:/https:\/\/GH_TOKEN@github.com\//' .gitmodules
 - git submodule update --init --recursive

install:
 - sh deploy.sh

notifications:
  email:
    - caio.f.r.amd@gmail.com
